name       : haskell-cryptohash-conduit
version    : 0.1.1
release    : 3
source     :
    - http://hackage.haskell.org/package/cryptohash-conduit-0.1.1/cryptohash-conduit-0.1.1.tar.gz : ea516d898d3e34dae6be3e8bc59c9f61a61cb1222233dbfe84a84bb0ded4b4ce
license    : BSD-3-Clause
component  : programming.haskell
summary    : Support all the cryptohash package using conduits from the conduit package.
description: |
    Support all the cryptohash package using conduits from the conduit package.
builddeps  :
    - haskell-cabal-install
    - haskell-conduit-extra-devel
    - haskell-cryptohash-devel
rundeps    :
    - devel:
        - haskell-conduit-extra-devel
        - haskell-cryptohash-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
